language: android
jdk: oraclejdk8
sudo: required
android:
  components:
    - tools
    - platform-tools
    - tools
    - build-tools-29.0.3
    - android-29
    - extra-android-m2repository
    - extra-google-m2repository
script:
  - "./gradlew clean build --stacktrace"
before_deploy:
  - jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 app/build/outputs/apk/release/app-release-unsigned.apk
    key -keystore keystore.jks -storepass $storepass -keypass $keypass
  - "${ANDROID_HOME}build-tools/29.0.3/zipalign 4 app/build/outputs/apk/release/app-release-unsigned.apk STTT.apk"
deploy:
  provider: releases
  api_key:
    secure: "BqkFd704vD7O0AMjriQ6oqd8Xa2eyC1JlQnrx38QZX67H3SivvgedfB9uObJxF8wd9FtAoqgVfMEGTkNtsa+EwqLmMN99INEM1pC4QxaKIRvpt5oob4ZEv1IRWWSseAPX6HMD4SmTyKNhETJ2zXpV0XYif2ORfJw5NKkaBwcPYtU0S/n+3Q0aoCE5mchcYVxwqDsDbmIaKXS9q9tO2w0mMHQpcH290IcTM/zfheKxIUziS/t+bOfDNrlO0cylbn3qLboAPRXMiGzJmqhclR72wGF8rG11wWZqyIUnhK45MC5ALX/kbqSmNB81oeZayP6RLHEyuVC1UF7nwMW3lrHnV+GC66+eNG45I6EUoXyZ1DhUZrwIJgMky8WDT+oVNZM5IUbl82NjXj29a1p+TAi7NugqIj7P7rO9sYsjF6nMGM+63083XMh1yWiu8uk7hNboCW42ugIGDQwnTxj4Xqi012HSNMYqDeqryYSdhPICaHzQV6rEli7gAVSwapFAFOU8c25FNizOvmijy+CEXH9v1mWkYeqEbq4zUO46qj4SSiDYMqIK1xwH+rC7cseDEFcqr9sauCKgh08dDdcytuPV2hi/XA2ZdPwYS2v0sR+IjKVgcCUNYKvY71bcbpF5Hvw/SxssmhcuHJbbUkETynv28jpfXDfEaRTqyH+3DVxwr4="
  file: STTT.apk
  skip_cleanup: true
  on:
    repo: henrykvdb/SuperTTTAndroid
    branch: master
    tags: true
env:
  global:
    - secure: WJvHRfpbt9eivAT8yYiPcTz5sPZ/Ys7SbMXWCZzCnlL6WJv40mIRZ+RN/mQZ9iqKf4QqG8h4x5zs5ix3XdI0WEs4VQZDKduUdvnRjKquGWJaMJBbOT/eWeq1AuLzgX4j7UHZkY2Df55ZAw9Mrst8M5m/zUw21b5qkfYXQa8Z1QxjMZ937xGheFZJAjN2JiMQobi2OvmP+gckEk1HCuIRVelaM7xT+Fg1nXU0iWAB8uZpRRbfcbsHhcrXbyJEzGDFiPxcLCt7a14ycunrLsdZ2CK6YPJXRTqacDCt8Uo7xZ4yxZYggdpw5eksaYkOBwo9w9LdYuT3uO/EIOEyKwpEs98I+XJj4osORgGM/BRD2HhZiiZ+BX0LTiIC3hUXhhyPXl/MVoLKig+xS9kd02NlwBcjX1+V5G0hcFSFPQIuQ8hQknXPsoJZqmB+gEnQEwWQnBOGkx8hKIqCUazaLMUAa9iam8AF3iNbc5GyOT7dbYZcJVNWMdBfLZMWW8W2/89seHa/fQ8QMDQDKZmWCMkQw3zY0RTpPDTBcMfe6gb/CWlqyedW4dhbClDic4tRK8DcjKsgZ3OiMk0voSLiAmIWyZIFfL//W/uNG39ITMHE2k1x30lnSeGk8uTJh5HQ8FIzAklUaQV6wtYMPY+9IgDUjPaud8leFGHQGXPyzlyO5NM=
    - secure: BO3hw7AkSOph4gqCylDistm29vxWyWoLF973VdyTZjTF+RIpQiMXgP91/26pio/1vZNRwLNpWzvK5w/3lbnDEnqGX/Z7unbLMA9ErYN6s6l69uaEpBwkRaTqtUE5ohZecKRHK3cWx8g20cxvuPPb0ON1NYeYJUzHYw4MihKKfoYjbcY9FChqwyKmmLo8SHBwdB46CYPDEjvijaY7MFMqxCtFTvXnfOBEgrUj7tnits9mZhocS55SuFLC4GBfw7dzV/CwtnY4KVqV9rW4jd8ceQS4LV9n6UPMh8Tt5L34JFCvJ5WtliISRMxFunpZ0cU9gG77oZIy56vqzJA+VydcqDvE5fFxrfzF51BAgsUj3Yk6io11bqbdaMiaTgHUqGDtceqV5CO44PC6RBKlogPi0+CS6v3yF96Ul17bCR0HfD0fy05F9CyMD1A9DuZIh5APpPZkZvXHDhzeWwKDpsdjoW9kzRmfdhN9333yV+5X08sOSB5qG36QbpWL1z7fb0e64dpr9gi7Y4pxUN1RtYPN7eNFjqt9CrS7mtuK3KC16WNTgXThx9kFIlu08S0B+gjwomv2bJhtvev0MVUvOPPm0d7JLwgeTtDg1KnvN5AsOVAunNd/C5hyMVkv/mSh4szBmxGa54DxPaJ2hDrG24WapAdr0AOLNz8gtHtZyYqGeSU=
before_install:
  - openssl aes-256-cbc -K $encrypted_bce35d79349a_key -iv $encrypted_bce35d79349a_iv
    -in keystore.jks.enc -out keystore.jks -d